create TABLE `t_device_fingerprint_source_log` (
  `reqtimestamp` varchar(50) NOT NULL COMMENT '请求时间戳',
  `deviceID` bigint(30) NOT NULL COMMENT '请求的指纹id',
  `uuid` vvarchar(50) DEFAULT NULL COMMENT 'uuid',
  `ua` varchar(50) DEFAULT NULL'ua',
  `platform` varchar(50) DEFAULT NULL COMMENT 'platform',
  `cookies_enable` varchar(255) DEFAULT NULL COMMENT 'cookies_enable',
  `timezone` varchar(20) DEFAULT NULL COMMENT 'timezone',
  `canvas_print` varchar(255) DEFAULT NULL COMMENT 'canvas_print',
  `plugins` varchar(255) DEFAULT NULL COMMENT 'plugins',
  `fonts` text COMMENT 'fonts',
  `screen_resolution` varchar(20) DEFAULT NULL COMMENT 'screen_resolution',
  `audio_formats` text COMMENT 'audio_formats',
  `video_formats` varchar(255) DEFAULT NULL COMMENT 'video_formats',
  `webgl_vendor` varchar(20) DEFAULT NULL COMMENT 'webgl_vendor',
  `webgl_renderer` varchar(20) DEFAULT NULL COMMENT 'webgl_renderer',
  `webgl_parameters` varchar(255) DEFAULT NULL COMMENT 'webgl_parameters',
  `cpu_info` varchar(255) DEFAULT NULL COMMENT 'cpu_info',
  `browser_name` text COMMENT 'browser_name',
  `browser_version` text COMMENT 'browser_version',
  `engine_info` text COMMENT'engine_info',
  `os_info` int(10) DEFAULT NULL COMMENT 'os_info',
  `language` text COMMENT  'language',
  `available_resolution` text COMMENT'可用尺寸',
  `mime_types` text DEFAULT NULL COMMENT '//支持的多媒体类型',
  `device_model` text COMMENT  '//设备品牌',
  `device_vendor` text COMMENT'//设备厂商',
  `is_mobile` text DEFAULT NULL COMMENT '//是否移动端',
  `storage_enable` text COMMENT  '//本地存储是否可用',
  `ret` int(8) DEFAULT NULL COMMENT '请求结果',
  `retDeviceID` varchar(30) DEFAULT NULL COMMENT '请求结果指纹ID',
  `usetime` varchar(50) NOT NULL COMMENT '请求使用时间',
  `reqticketid` text COMMENT'请求ticketid',
  `respticketID` text COMMENT'返回ticketid',
  `channel` varchar(20) NOT NULL COMMENT '渠道',
  `lc` text COMMENT'lc',
  `product_clientVer` text COMMENT'接入方版本号',
  `product_pkg` text COMMENT'接入方包名',
  `client_metaData` text COMMENT'接入方填写自定义信息',
  `client_channel` text COMMENT'接入方客户端的渠道号',
  `client_version` text COMMENT'接入方客户端的版本号',
  `client_requestSeq` text COMMENT'用户标识当次请求',
  `client_buildNo` text COMMENT'接入方客户端的build号',
  `client_lc` text COMMENT'接入方客户端的lc',
  `client_extraInfo` text COMMENT'扩展字段',
  `openID` text COMMENT'接入渠道的openid',
  `buildno` text COMMENT'客户端SDKbuildno',
  `scene` text COMMENT'服务端处理场景',
  `client_ip` text COMMENT'客户端ip',
  `audio_print` text COMMENT'音频指纹',
  `media_devices` text COMMENT'media列表',
  PRIMARY KEY (`reqID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='存储请求日志'